create table if not exists public.users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  password_hash text not null,
  role text not null default 'production' check (role in ('admin', 'production', 'warehouse')),
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null default 'Umum',
  price numeric not null default 0,
  stock numeric not null default 0,
  owner_id bigint references public.users(id) on delete set null,
  image_url text,
  created_at timestamptz not null default now()
);

insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do update set public = excluded.public;

alter table public.users enable row level security;
alter table public.products enable row level security;

-- Run this block when upgrading an existing project created with the old role list.
alter table public.users drop constraint if exists users_role_check;
update public.users set role = 'production' where role = 'staff';
alter table public.users add constraint users_role_check check (role in ('admin', 'production', 'warehouse'));

-- The backend uses SUPABASE_SECRET_KEY and performs authorization in Express.
-- No public client policy is granted for this interview application.
